// Mock Data para HOKMA

export const mockUser = {
  id: '1',
  name: 'Ricardo Almeida',
  email: 'ricardo@hokma.com.br',
  avatar: '',
  role: 'admin' as const,
}

export const mockTenants = [
  { id: '1', name: 'Imobiliária Premium', logo: '' },
  { id: '2', name: 'Construtora Elite', logo: '' },
  { id: '3', name: 'Real Estate Corp', logo: '' },
]

export const mockDashboardStats = {
  leadsDoMes: { value: 247, change: 12.5 },
  clientesAtivos: { value: 1842, change: 8.3 },
  tarefasPendentes: { value: 34, change: -5.2 },
  agendamentosHoje: { value: 12, change: 0 },
  empreendimentosAtivos: { value: 8, change: 25 },
  receitaEstimada: { value: 2450000, change: 15.8 },
}

export const mockFunnelData = [
  { stage: 'Novos', count: 145, percentage: 100 },
  { stage: 'Em Atendimento', count: 98, percentage: 67.6 },
  { stage: 'Proposta', count: 52, percentage: 35.9 },
  { stage: 'Negociação', count: 28, percentage: 19.3 },
  { stage: 'Fechado', count: 18, percentage: 12.4 },
]

export const mockTeamPerformance = [
  { name: 'Ana Silva', vendas: 12, leads: 45, conversao: 26.7 },
  { name: 'Carlos Souza', vendas: 10, leads: 38, conversao: 26.3 },
  { name: 'Maria Santos', vendas: 8, leads: 42, conversao: 19.0 },
  { name: 'Pedro Lima', vendas: 7, leads: 35, conversao: 20.0 },
  { name: 'Julia Costa', vendas: 6, leads: 30, conversao: 20.0 },
]

export const mockRecentActivities = [
  { id: '1', type: 'lead', message: 'Novo lead cadastrado: João Mendes', time: '5 min atrás', user: 'Ana Silva' },
  { id: '2', type: 'visit', message: 'Visita agendada: Residencial Aurora', time: '12 min atrás', user: 'Carlos Souza' },
  { id: '3', type: 'proposal', message: 'Proposta enviada: Apartamento 302', time: '25 min atrás', user: 'Maria Santos' },
  { id: '4', type: 'sale', message: 'Venda concluída: Casa Jardim Europa', time: '1 hora atrás', user: 'Pedro Lima' },
  { id: '5', type: 'task', message: 'Tarefa concluída: Ligar para cliente', time: '2 horas atrás', user: 'Julia Costa' },
]

export const mockClients = [
  {
    id: '1',
    name: 'João Mendes',
    email: 'joao.mendes@email.com',
    phone: '(11) 99999-1234',
    status: 'novo',
    corretor: 'Ana Silva',
    interesse: 'Apartamento 2 quartos',
    prioridade: 'alta',
    rendaMensal: 18500,
    orcamento: 780000,
    ultimoContato: new Date('2024-01-15'),
    tags: ['Investidor', 'Alto padrão'],
  },
  {
    id: '2',
    name: 'Maria Oliveira',
    email: 'maria.oliveira@email.com',
    phone: '(11) 98888-5678',
    status: 'em_atendimento',
    corretor: 'Carlos Souza',
    interesse: 'Casa térrea',
    prioridade: 'media',
    rendaMensal: 12200,
    orcamento: 620000,
    ultimoContato: new Date('2024-01-14'),
    tags: ['Família', 'Primeira compra'],
  },
  {
    id: '3',
    name: 'Pedro Costa',
    email: 'pedro.costa@email.com',
    phone: '(11) 97777-9012',
    status: 'proposta',
    corretor: 'Maria Santos',
    interesse: 'Cobertura',
    prioridade: 'alta',
    rendaMensal: 24000,
    orcamento: 1200000,
    ultimoContato: new Date('2024-01-13'),
    tags: ['Premium', 'Vista mar'],
  },
  {
    id: '4',
    name: 'Ana Ferreira',
    email: 'ana.ferreira@email.com',
    phone: '(11) 96666-3456',
    status: 'negociacao',
    corretor: 'Pedro Lima',
    interesse: 'Apartamento 3 quartos',
    prioridade: 'alta',
    rendaMensal: 16000,
    orcamento: 890000,
    ultimoContato: new Date('2024-01-12'),
    tags: ['Upgrade', 'Financiamento'],
  },
  {
    id: '5',
    name: 'Lucas Santos',
    email: 'lucas.santos@email.com',
    phone: '(11) 95555-7890',
    status: 'fechado',
    corretor: 'Julia Costa',
    interesse: 'Studio',
    prioridade: 'baixa',
    rendaMensal: 9800,
    orcamento: 410000,
    ultimoContato: new Date('2024-01-11'),
    tags: ['Jovem profissional'],
  },
  {
    id: '6',
    name: 'Carla Rodrigues',
    email: 'carla.rodrigues@email.com',
    phone: '(11) 94444-1234',
    status: 'perdido',
    corretor: 'Ana Silva',
    interesse: 'Lote',
    prioridade: 'baixa',
    rendaMensal: 7600,
    orcamento: 280000,
    ultimoContato: new Date('2024-01-10'),
    tags: ['Construção própria'],
  },
]

export const mockEmpreendimentos = [
  {
    id: '1',
    nome: 'Residencial Aurora',
    status: 'em_lancamento',
    endereco: 'Rua das Flores, 245',
    localizacao: 'Jardim Europa, São Paulo',
    cidade: 'São Paulo',
    responsavel: 'Carlos Souza',
    construtora: 'Hokma Desenvolvimento Urbano',
    unidades: 120,
    totalUnidades: 120,
    unidadesDisponiveis: 45,
    precoInicial: 650000,
    precoMinimo: 650000,
    precoMaximo: 980000,
    imagem: '/placeholder.svg?height=200&width=300',
  },
  {
    id: '2',
    nome: 'Edifício Cristal',
    status: 'em_construcao',
    endereco: 'Av. Cristal, 890',
    localizacao: 'Vila Olímpia, São Paulo',
    cidade: 'São Paulo',
    responsavel: 'Maria Santos',
    construtora: 'Cristal Engenharia',
    unidades: 80,
    totalUnidades: 80,
    unidadesDisponiveis: 22,
    precoInicial: 890000,
    precoMinimo: 890000,
    precoMaximo: 1350000,
    imagem: '/placeholder.svg?height=200&width=300',
  },
  {
    id: '3',
    nome: 'Condomínio Parque Verde',
    status: 'pronto',
    endereco: 'Alameda Verde, 1120',
    localizacao: 'Moema, São Paulo',
    cidade: 'São Paulo',
    responsavel: 'Pedro Lima',
    construtora: 'Parque Verde Construtora',
    unidades: 200,
    totalUnidades: 200,
    unidadesDisponiveis: 8,
    precoInicial: 520000,
    precoMinimo: 520000,
    precoMaximo: 860000,
    imagem: '/placeholder.svg?height=200&width=300',
  },
  {
    id: '4',
    nome: 'Torres do Lago',
    status: 'em_lancamento',
    endereco: 'Av. dos Lagos, 77',
    localizacao: 'Alphaville, Barueri',
    cidade: 'Barueri',
    responsavel: 'Ana Silva',
    construtora: 'Torres Holding Imobiliaria',
    unidades: 150,
    totalUnidades: 150,
    unidadesDisponiveis: 150,
    precoInicial: 750000,
    precoMinimo: 750000,
    precoMaximo: 1120000,
    imagem: '/placeholder.svg?height=200&width=300',
  },
]

export const mockTarefas = [
  {
    id: '1',
    titulo: 'Ligar para João Mendes',
    descricao: 'Retornar ligação sobre interesse no Residencial Aurora',
    status: 'pendente',
    prioridade: 'alta',
    prazo: new Date('2024-01-16'),
    responsavel: 'Ana Silva',
    cliente: 'João Mendes',
  },
  {
    id: '2',
    titulo: 'Enviar proposta',
    descricao: 'Preparar e enviar proposta comercial para Maria Oliveira',
    status: 'em_andamento',
    prioridade: 'alta',
    prazo: new Date('2024-01-17'),
    responsavel: 'Carlos Souza',
    cliente: 'Maria Oliveira',
  },
  {
    id: '3',
    titulo: 'Agendar visita',
    descricao: 'Agendar visita ao empreendimento Edifício Cristal',
    status: 'pendente',
    prioridade: 'media',
    prazo: new Date('2024-01-18'),
    responsavel: 'Maria Santos',
    cliente: 'Pedro Costa',
  },
  {
    id: '4',
    titulo: 'Atualizar documentação',
    descricao: 'Atualizar documentação de venda para Ana Ferreira',
    status: 'concluida',
    prioridade: 'baixa',
    prazo: new Date('2024-01-15'),
    responsavel: 'Pedro Lima',
    cliente: 'Ana Ferreira',
  },
]

export const mockAgenda = [
  {
    id: '1',
    titulo: 'Visita Residencial Aurora',
    tipo: 'visita',
    data: new Date('2024-01-16T10:00:00'),
    duracao: 60,
    cliente: 'João Mendes',
    local: 'Residencial Aurora - Show Room',
    responsavel: 'Ana Silva',
  },
  {
    id: '2',
    titulo: 'Reunião de equipe',
    tipo: 'reuniao',
    data: new Date('2024-01-16T14:00:00'),
    duracao: 45,
    cliente: null,
    local: 'Sala de Reuniões',
    responsavel: 'Ricardo Almeida',
  },
  {
    id: '3',
    titulo: 'Apresentação Edifício Cristal',
    tipo: 'apresentacao',
    data: new Date('2024-01-16T16:00:00'),
    duracao: 90,
    cliente: 'Pedro Costa',
    local: 'Stand de Vendas',
    responsavel: 'Maria Santos',
  },
]

export const mockConversas = [
  {
    id: '1',
    participante: { nome: 'João Mendes', avatar: '', online: true },
    ultimaMensagem: 'Olá, gostaria de agendar uma visita',
    dataUltimaMensagem: new Date('2024-01-15T15:30:00'),
    naoLidas: 2,
  },
  {
    id: '2',
    participante: { nome: 'Maria Oliveira', avatar: '', online: false },
    ultimaMensagem: 'Obrigada pela proposta, vou analisar',
    dataUltimaMensagem: new Date('2024-01-15T14:00:00'),
    naoLidas: 0,
  },
  {
    id: '3',
    participante: { nome: 'Carlos Souza', avatar: '', online: true },
    ultimaMensagem: 'Podemos conversar sobre o cliente?',
    dataUltimaMensagem: new Date('2024-01-15T12:30:00'),
    naoLidas: 1,
  },
]

export const mockMensagens = [
  {
    id: '1',
    conversaId: '1',
    remetente: 'João Mendes',
    conteudo: 'Olá, boa tarde!',
    data: new Date('2024-01-15T15:00:00'),
    enviada: false,
  },
  {
    id: '2',
    conversaId: '1',
    remetente: 'Você',
    conteudo: 'Olá João! Tudo bem? Em que posso ajudar?',
    data: new Date('2024-01-15T15:05:00'),
    enviada: true,
  },
  {
    id: '3',
    conversaId: '1',
    remetente: 'João Mendes',
    conteudo: 'Gostaria de saber mais sobre o Residencial Aurora',
    data: new Date('2024-01-15T15:10:00'),
    enviada: false,
  },
  {
    id: '4',
    conversaId: '1',
    remetente: 'João Mendes',
    conteudo: 'Olá, gostaria de agendar uma visita',
    data: new Date('2024-01-15T15:30:00'),
    enviada: false,
  },
]

export const mockPortais = [
  {
    id: '1',
    nome: 'ZAP Imóveis',
    status: 'ativo',
    integracaoStatus: 'sincronizado',
    ultimaSincronizacao: new Date('2024-01-15T12:00:00'),
    anunciosAtivos: 45,
    leads: 128,
  },
  {
    id: '2',
    nome: 'Viva Real',
    status: 'ativo',
    integracaoStatus: 'sincronizado',
    ultimaSincronizacao: new Date('2024-01-15T11:30:00'),
    anunciosAtivos: 42,
    leads: 95,
  },
  {
    id: '3',
    nome: 'OLX',
    status: 'ativo',
    integracaoStatus: 'pendente',
    ultimaSincronizacao: new Date('2024-01-14T18:00:00'),
    anunciosAtivos: 38,
    leads: 67,
  },
  {
    id: '4',
    nome: 'Imovelweb',
    status: 'inativo',
    integracaoStatus: 'erro',
    ultimaSincronizacao: new Date('2024-01-10T10:00:00'),
    anunciosAtivos: 0,
    leads: 23,
  },
]

export const mockUsuarios = [
  {
    id: '1',
    nome: 'Ricardo Almeida',
    email: 'ricardo@hokma.com.br',
    perfil: 'Administrador',
    status: 'ativo',
    permissoes: ['admin', 'gerenciar_usuarios', 'relatorios'],
    avatar: '',
  },
  {
    id: '2',
    nome: 'Ana Silva',
    email: 'ana.silva@hokma.com.br',
    perfil: 'Corretor',
    status: 'ativo',
    permissoes: ['vendas', 'clientes'],
    avatar: '',
  },
  {
    id: '3',
    nome: 'Carlos Souza',
    email: 'carlos.souza@hokma.com.br',
    perfil: 'Gerente',
    status: 'ativo',
    permissoes: ['gerenciar_equipe', 'relatorios', 'vendas'],
    avatar: '',
  },
  {
    id: '4',
    nome: 'Maria Santos',
    email: 'maria.santos@hokma.com.br',
    perfil: 'Corretor',
    status: 'ativo',
    permissoes: ['vendas', 'clientes'],
    avatar: '',
  },
  {
    id: '5',
    nome: 'Pedro Lima',
    email: 'pedro.lima@hokma.com.br',
    perfil: 'Corretor',
    status: 'inativo',
    permissoes: ['vendas', 'clientes'],
    avatar: '',
  },
]

export const mockEquipes = [
  {
    id: '1',
    nome: 'Equipe Alpha',
    lider: 'Carlos Souza',
    membros: 5,
    metaMensal: 500000,
    vendas: 380000,
    desempenho: 76,
  },
  {
    id: '2',
    nome: 'Equipe Beta',
    lider: 'Maria Santos',
    membros: 4,
    metaMensal: 400000,
    vendas: 420000,
    desempenho: 105,
  },
  {
    id: '3',
    nome: 'Equipe Gamma',
    lider: 'Pedro Lima',
    membros: 3,
    metaMensal: 300000,
    vendas: 210000,
    desempenho: 70,
  },
]

export const mockNotifications = [
  {
    id: '1',
    title: 'Novo lead cadastrado',
    message: 'João Mendes foi cadastrado como novo lead',
    type: 'info' as const,
    read: false,
    createdAt: new Date('2024-01-15T15:30:00'),
  },
  {
    id: '2',
    title: 'Venda concluída',
    message: 'Parabéns! Venda do apartamento 302 foi finalizada',
    type: 'success' as const,
    read: false,
    createdAt: new Date('2024-01-15T14:00:00'),
  },
  {
    id: '3',
    title: 'Tarefa atrasada',
    message: 'A tarefa "Ligar para cliente" está atrasada',
    type: 'warning' as const,
    read: true,
    createdAt: new Date('2024-01-15T10:00:00'),
  },
]

export const mockChartData = {
  vendasMensais: [
    { mes: 'Jan', vendas: 12, meta: 15 },
    { mes: 'Fev', vendas: 18, meta: 15 },
    { mes: 'Mar', vendas: 15, meta: 18 },
    { mes: 'Abr', vendas: 22, meta: 18 },
    { mes: 'Mai', vendas: 19, meta: 20 },
    { mes: 'Jun', vendas: 25, meta: 20 },
  ],
  leadsPorOrigem: [
    { origem: 'Site', leads: 45 },
    { origem: 'ZAP', leads: 38 },
    { origem: 'Indicação', leads: 28 },
    { origem: 'Redes Sociais', leads: 22 },
    { origem: 'Outros', leads: 12 },
  ],
}
